spring:
  batch:
    jdbc:
      initialize-schema: never

mybatis:
  type-aliases-package: org.example.model
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 60
    jdbc-type-for-null: "NULL"