database:
  driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:test
  username: user12
  password: password12
  max-lifetime: 0
  idle-timeout: 0
  connection-timeout: 10000
  maximum-pool-size: 5
